
const state={view:'inici',filter:{q:'',unitat:'',tema:'',tipus:'',nivell:''},current:null,progress:JSON.parse(localStorage.getItem('ti2-progress')||'{}'),teacher:JSON.parse(localStorage.getItem('ti2-teacher')||'{}')};
const views=['Inici','Temes','Exercicis','Calculadores','Pràctica','Docent','Progrés','Auditoria','Ajuda'];
function $(s){return document.querySelector(s)}; function esc(s){return String(s||'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}
function nav(){ $('#nav').innerHTML=views.map(v=>`<button class="tab ${state.view==v.toLowerCase()?'active':''}" onclick="go('${v.toLowerCase()}')">${v}</button>`).join('') }
function go(v){state.view=v; state.current=null; render(); window.scrollTo(0,0)}
function uniq(a){return [...new Set(a.filter(Boolean))].sort((a,b)=>a.localeCompare(b,'ca'))}

function cleanExtractedText(txt){
  let s=String(txt||'');
  s=s.replace(/Bach_Sol[^\s]*/g,' ');
  s=s.replace(/\/MT\d+/g,' ');
  s=s.replace(/[\u0000-\u001f\u007f]/g,' ');
  s=s.replace(/￾/g,'');
  s=s.replace(/([a-zà-ÿ])-\s+([a-zà-ÿ])/gi,'$1$2');
  s=s.replace(/\s+/g,' ').trim();
  s=s.replace(/([.!?])\s+/g,'$1\n');
  s=s.replace(/(\b[abcde]\))/g,'\n$1');
  s=s.replace(/(\b\d+\.)\s+(?=[A-ZÀ-Ú])/g,'\n$1 ');
  s=s.replace(/\s*([=+−*/·])\s*/g,' $1 ');
  s=s.replace(/\s{2,}/g,' ');
  return s.trim();
}
function paragraphsFromClean(s){
  const txt=cleanExtractedText(s);
  if(!txt) return '<p>No hi ha solució textual depurada disponible. Consulta la pàgina original i fes servir el procediment guiat.</p>';
  return txt.split(/\n+/).filter(Boolean).slice(0,14).map(x=>`<p>${esc(x)}</p>`).join('');
}
function filtered(){let f=state.filter; return EXERCISES.filter(e=>(!f.q||JSON.stringify(e).toLowerCase().includes(f.q.toLowerCase()))&&(!f.unitat||e.unitat==f.unitat)&&(!f.tema||e.tema==f.tema)&&(!f.tipus||e.tipus==f.tipus)&&(!f.nivell||e.nivell==f.nivell))}
function filters(){let us=uniq(EXERCISES.map(e=>e.unitat)), ts=uniq(EXERCISES.map(e=>e.tema)), ty=uniq(EXERCISES.map(e=>e.tipus)), ns=uniq(EXERCISES.map(e=>e.nivell)); return `<div class="card noprint"><h2>Filtres</h2><div class="grid"><label>Cerca<input value="${esc(state.filter.q)}" placeholder="motor, gas, lògica, metrologia..." oninput="state.filter.q=this.value;render()"></label><label>Unitat<select onchange="state.filter.unitat=this.value;render()"><option value="">Totes</option>${us.map(x=>`<option ${state.filter.unitat==x?'selected':''}>${esc(x)}</option>`).join('')}</select></label><label>Tema<select onchange="state.filter.tema=this.value;render()"><option value="">Tots</option>${ts.map(x=>`<option ${state.filter.tema==x?'selected':''}>${esc(x)}</option>`).join('')}</select></label><label>Tipus<select onchange="state.filter.tipus=this.value;render()"><option value="">Tots</option>${ty.map(x=>`<option ${state.filter.tipus==x?'selected':''}>${esc(x)}</option>`).join('')}</select></label><label>Nivell<select onchange="state.filter.nivell=this.value;render()"><option value="">Tots</option>${ns.map(x=>`<option ${state.filter.nivell==x?'selected':''}>${esc(x)}</option>`).join('')}</select></label></div></div>`}
function card(e){let st=state.teacher[e.id]?.status||'pendent'; return `<article class="card"><span class="pill">${esc(e.unitat)}</span><span class="pill">${esc(e.tema)}</span><h3>${esc(e.titol)}</h3><p class="muted">${esc(e.enunciat).slice(0,260)}${e.enunciat.length>260?'...':''}</p><p><b>Pàgina:</b> ${e.page} · <b>Tipus:</b> ${esc(e.tipus)} · <b>Nivell:</b> ${esc(e.nivell)} · <b>Estat:</b> ${esc(st)}</p><button class="btn primary" onclick="openEx('${e.id}')">Obrir exercici</button><button class="btn" onclick="printEx('${e.id}')">Fitxa imprimible</button></article>`}
function openEx(id){state.current=EXERCISES.find(e=>e.id==id); state.view='exercicis'; render(); window.scrollTo(0,0)}
function solution(e){return `<div class="solution"><h3>Resolució guiada</h3><h4>1. Què demana?</h4><p>Identifica la magnitud o decisió tècnica que cal obtenir en aquest exercici de <b>${esc(e.tema)}</b>.</p><h4>2. Dades i unitats</h4><p>Extreu les dades numèriques de l’enunciat i converteix-les al SI quan calgui. Si hi ha figura, consulta la pàgina original.</p><h4>3. Fórmules o principis</h4>${e.formules.map(f=>`<code class="formula">${esc(f)}</code>`).join('')}<h4>4. Desenvolupament</h4><p>Substitueix les dades de manera ordenada. Escriu unitats a cada pas i comprova si el resultat té sentit físic o tecnològic.</p><h4>5. Solució model depurada</h4><div class="clean-solution">${paragraphsFromClean(e.solucioBase)}</div><p class="notice"><b>Nota docent:</b> aquesta solució s’ha netejat automàticament a partir del text extret. Quan hi hagi fórmules complexes, gràfics o esquemes, revisa també la pàgina original integrada.</p><details class="noprint"><summary><b>Veure text extret original</b></summary><div class="rawbox">${esc(e.solucioBase)}</div></details><h4>6. Errors habituals</h4><ul><li>No convertir rpm a rad/s, bar a Pa, mm a m o hores a segons.</li><li>Confondre potència i energia.</li><li>Donar el número final sense unitat ni interpretació.</li><li>En test, no justificar per què les altres opcions són incorrectes.</li></ul></div>`}
function exerciseView(){if(state.current){let e=state.current;return `<div class="card"><button class="btn noprint" onclick="state.current=null;render()">← Tornar al banc</button><h2>${esc(e.titol)}</h2><p><span class="pill">${esc(e.bloc)}</span><span class="pill">${esc(e.unitat)}</span><span class="pill">${esc(e.tema)}</span><span class="pill">${esc(e.tipus)}</span></p><h3>Enunciat de treball</h3><p>${esc(e.enunciat)}</p><div class="row noprint"><button class="btn primary" onclick="markDone('${e.id}')">Marcar com fet</button><button class="btn" onclick="window.print()">Imprimir fitxa</button><button class="btn" onclick="showPage(${e.page})">Veure pàgina original</button></div><details open><summary><b>Solució pas a pas</b></summary>${solution(e)}</details><details><summary><b>Pàgina original del solucionari</b></summary><p class="muted">S’utilitza per revisar figures, gràfics o esquemes que no quedin ben reflectits al text extret.</p><img class="pageimg" src="assets/pages/page-${String(e.page).padStart(3,'0')}.jpg"></details></div>`} let list=filtered(); return filters()+`<h2>${list.length} fitxes trobades</h2><div class="grid">${list.slice(0,300).map(card).join('')}</div><p class="muted">Si el filtre retorna moltes fitxes, usa unitat o paraula clau. El banc prové del solucionari de 2n i pot contenir activitats, qüestions finals, exercicis i avaluacions.</p>`}
function showPage(p){let w=window.open('assets/pages/page-'+String(p).padStart(3,'0')+'.jpg','_blank');}
function markDone(id){state.progress[id]={done:true,date:new Date().toISOString()}; localStorage.setItem('ti2-progress',JSON.stringify(state.progress)); alert('Exercici marcat com fet.');}
function printEx(id){openEx(id); setTimeout(()=>window.print(),250)}
function inicio(){let units=uniq(EXERCISES.map(e=>e.unitat));let temes=uniq(EXERCISES.map(e=>e.tema));return `<section class="card"><h2>PWA de Tecnologia Industrial 2n BATX</h2><p>Aquesta variant està centrada en el <b>solucionari de 2n de Batxillerat</b>. Permet cercar exercicis per unitat, tema i nivell, veure la pàgina original, treballar la resolució per passos i preparar dossiers o activitats de classe.</p><div class="row"><button class="btn primary" onclick="go('exercicis')">Obrir banc d’exercicis</button><button class="btn" onclick="go('calculadores')">Calculadores</button><button class="btn" onclick="go('docent')">Mode docent</button></div></section><section class="grid"><div class="card"><h3>${EXERCISES.length}</h3><p>fitxes detectades del PDF.</p></div><div class="card"><h3>${units.length}</h3><p>unitats didàctiques.</p></div><div class="card"><h3>${temes.length}</h3><p>temes transversals.</p></div></section><section class="card"><h2>Blocs inclosos</h2><p>${uniq(EXERCISES.map(e=>e.bloc)).map(x=>`<span class="pill">${esc(x)}</span>`).join('')}</p></section>`}
function temes(){let m={}; EXERCISES.forEach(e=>{m[e.tema]=(m[e.tema]||0)+1});return `<h2>Temes de 2n BATX</h2><div class="grid">${Object.entries(m).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<div class="card"><h3>${esc(k)}</h3><p>${v} fitxes</p><button class="btn" onclick="state.filter.tema='${esc(k)}';go('exercicis')">Veure exercicis</button></div>`).join('')}</div>`}
function calc(){return `<div class="card"><h2>Calculadores de 2n BATX</h2><p>Selecciona una eina ràpida. Les calculadores són de suport i no substitueixen la resolució escrita.</p><label>Tipus<select id="calcType"><option value="torque">Parell i potència</option><option value="heat">Calor Q=m·ce·ΔT</option><option value="gas">Gas ideal pV=nRT</option><option value="hyd">Cilindre hidràulic F=p·A</option><option value="rl">Reactància inductiva XL</option><option value="tri">Trifàsica P=√3·U·I·cosφ</option></select></label><div id="calcFields" class="grid"></div><button class="btn primary" onclick="runCalc()">Calcular amb explicació</button><div id="calcOut" class="result"></div></div>`}
function setCalcFields(){let t=$('#calcType')?.value;if(!t)return;let html='';let fields={torque:[['P','Potència (W)',3000],['n','Velocitat (min⁻¹)',1450]],heat:[['m','Massa (kg)',10],['ce','Calor específica (J/kg·K)',4180],['dt','Increment T (K)',40]],gas:[['n','Mols',1],['T','Temperatura (K)',293],['V','Volum (m³)',0.02]],hyd:[['p','Pressió (bar)',80],['d','Diàmetre (mm)',50]],rl:[['f','Freqüència (Hz)',50],['L','Inductància (H)',0.2]],tri:[['U','Tensió composta (V)',400],['I','Intensitat (A)',10],['c','cos φ',0.8]]}[t]; fields.forEach(([id,lab,val])=>html+=`<label>${lab}<input id="c_${id}" type="number" step="any" value="${val}"></label>`); $('#calcFields').innerHTML=html}
function runCalc(){let t=$('#calcType').value,v=id=>parseFloat($('#c_'+id).value)||0,out=''; if(t=='torque'){let w=2*Math.PI*v('n')/60, M=v('P')/w;out=`<h3>Parell</h3><code class="formula">ω = 2πn/60 = ${w.toFixed(3)} rad/s</code><code class="formula">Γ = P/ω = ${M.toFixed(3)} N·m</code>`} if(t=='heat'){let Q=v('m')*v('ce')*v('dt');out=`<h3>Calor</h3><code class="formula">Q = m·ce·ΔT = ${Q.toFixed(2)} J = ${(Q/1000).toFixed(2)} kJ</code>`} if(t=='gas'){let p=v('n')*8.314*v('T')/v('V');out=`<h3>Gas ideal</h3><code class="formula">p = nRT/V = ${p.toFixed(0)} Pa = ${(p/100000).toFixed(3)} bar</code>`} if(t=='hyd'){let A=Math.PI*Math.pow(v('d')/1000,2)/4,F=v('p')*1e5*A;out=`<h3>Cilindre hidràulic</h3><code class="formula">A = πd²/4 = ${A.toExponential(3)} m²</code><code class="formula">F = p·A = ${F.toFixed(1)} N</code>`} if(t=='rl'){let XL=2*Math.PI*v('f')*v('L');out=`<h3>Reactància inductiva</h3><code class="formula">XL = 2πfL = ${XL.toFixed(2)} Ω</code>`} if(t=='tri'){let P=Math.sqrt(3)*v('U')*v('I')*v('c');out=`<h3>Potència trifàsica</h3><code class="formula">P = √3·U·I·cosφ = ${P.toFixed(1)} W</code>`} $('#calcOut').innerHTML=out}
function practica(){let e=EXERCISES[Math.floor(Math.random()*EXERCISES.length)];return `<div class="card"><h2>Pràctica ràpida</h2><p>Exercici proposat aleatoriament:</p>${card(e)}<button class="btn primary" onclick="go('pràctica')">Generar-ne un altre</button></div>`}
function docent(){let n=filtered().length;return filters()+`<div class="card"><h2>Mode docent</h2><p>Prepara classe amb el banc de 2n. Filtra per unitat o tema i imprimeix un dossier d’alumne o un solucionari orientatiu.</p><div class="row"><button class="btn primary" onclick="printDossier(false)">Imprimir dossier d’alumne (${n})</button><button class="btn" onclick="printDossier(true)">Imprimir solucionari docent (${n})</button></div></div>`}
function printDossier(sol){let list=filtered().slice(0,30);let html=list.map(e=>`<div class="card"><h2>${esc(e.titol)}</h2><p>${esc(e.enunciat)}</p>${sol?solution(e):'<p><b>Espai de resposta:</b></p><br><br><br>'}</div>`).join(''); let old=$('#app').innerHTML; $('#app').innerHTML=html; window.print(); $('#app').innerHTML=old;}
function progres(){let done=Object.keys(state.progress).length;return `<div class="card"><h2>Progrés local</h2><p>Exercicis marcats com fets en aquest navegador: <b>${done}</b></p><button class="btn" onclick="localStorage.removeItem('ti2-progress');state.progress={};render()">Esborrar progrés</button><button class="btn" onclick="downloadJSON()">Exportar progrés</button></div>`}
function downloadJSON(){let blob=new Blob([JSON.stringify(state.progress,null,2)],{type:'application/json'});let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='progres_ti2batx.json';a.click()}
function auditoria(){let statuses=['pendent','verificat','revisar resultat','depèn de figura','millorar enunciat']; let list=filtered().slice(0,80);return filters()+`<div class="card"><h2>Auditoria docent</h2><p>Marca l’estat de cada fitxa. Les marques es guarden només al navegador.</p></div><div class="grid">${list.map(e=>`<div class="card"><h3>${esc(e.titol)}</h3><p>${esc(e.enunciat).slice(0,180)}...</p><select onchange="state.teacher['${e.id}']={status:this.value};localStorage.setItem('ti2-teacher',JSON.stringify(state.teacher))">${statuses.map(s=>`<option ${state.teacher[e.id]?.status==s?'selected':''}>${s}</option>`).join('')}</select></div>`).join('')}</div>`}
function ajuda(){return `<div class="card"><h2>Ajuda ràpida</h2><h3>Com començar?</h3><ol><li>Ves a <b>Temes</b> i tria el bloc que vols treballar.</li><li>Obre una fitxa i demana a l’alumnat que identifiqui dades, fórmula i unitats.</li><li>Mostra la solució pas a pas només després de la primera resolució.</li><li>Usa <b>Docent</b> per imprimir dossiers filtrats.</li></ol><h3>Què volen dir N1-N4?</h3><p>N1 identifica dades, N2 calcula, N3 interpreta i N4 justifica o compara.</p><h3>Avís</h3><p>El banc és una transformació didàctica del solucionari aportat. Les fitxes complexes o amb figures s’han de revisar abans d’usar-les com a solucionari definitiu.</p></div>`}
function render(){nav(); let v=state.view; $('#app').innerHTML = v=='inici'?inicio():v=='temes'?temes():v=='exercicis'?exerciseView():v=='calculadores'?calc():v=='pràctica'?practica():v=='docent'?docent():v=='progrés'?progres():v=='auditoria'?auditoria():ajuda(); if(v=='calculadores'){setCalcFields(); $('#calcType').addEventListener('change',setCalcFields)}}
render();
